name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

env:
  CARGO_TERM_COLOR: always

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    env:
      RESULT_FILE: rust-clippy-results.sarif

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install sarif crates
        run: cargo install clippy-sarif sarif-fmt

      - name: Run clippy
        run:
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee ${{ env.RESULT_FILE }} | sarif-fmt

      - name: Upload analysis results
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ env.RESULT_FILE }}
          wait-for-processing: true

  fmt:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Check Code Style
        run: cargo fmt --check

  build:
    runs-on: ubuntu-latest
    needs: [analyze, fmt]

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: cargo build
